Half-way
hiroki189/chat-space pull request #1
Opened 2019-04-27 10:18 UTC by hiroki189

2019-04-27 10:24 UTC, hiroki189 commented
画面実装をひと段落させたので、コードレビューお願いします。

2019-04-27 10:29 UTC, TOMARUMARU reviewed
BEMと&記法を使いましょう

2019-04-27 10:29 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-04-27 10:29 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +!!!
mailerファイル使用しないので削除しましょう

2019-04-27 10:29 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> += yield
mailerファイル使用しないので削除しましょう

2019-04-27 10:29 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'messages' => 'messages#index'
rootに設定しましょう

2019-04-28 06:21 UTC, hiroki189 commented
修正しました。

2019-04-28 06:32 UTC, hiroki189 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/

2019-04-28 06:32 UTC, hiroki189 commented on app/views/layouts/mailer.html.haml
> +!!!
指摘箇所の削除。

2019-04-28 06:32 UTC, hiroki189 commented on app/views/layouts/mailer.text.haml
> += yield
削除

2019-04-28 06:33 UTC, hiroki189 commented on config/routes.rb
> +  get 'messages' => 'messages#index'
root 'messages#index'

2019-04-28 06:36 UTC, ghost requested changes

2019-04-28 06:36 UTC, hiroki5123 commented on Gemfile
> +gem "font-awesome-rails"
最後に空行いれてください。

2019-04-28 06:36 UTC, hiroki5123 commented on app/assets/stylesheets/_stylesheets.scss
> +}
最後に空行いれてください。

2019-04-28 06:36 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        SEND
最後に空行いれてください。

2019-04-28 06:36 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +      %ul.chat-main__header__current-group_list
ulはliと組み合わせて使います

2019-04-28 06:36 UTC, hiroki5123 commented
実際の画面のキャプチャをこちらに添付してください

2019-04-28 07:42 UTC, hiroki189 commented on app/assets/stylesheets/_stylesheets.scss
> +}
入れました

2019-04-28 07:42 UTC, hiroki189 commented on Gemfile
> +gem "font-awesome-rails"
入れました

2019-04-28 07:42 UTC, hiroki189 commented on app/views/messages/index.html.haml
> +        SEND
しました

2019-04-28 07:46 UTC, hiroki189 commented on app/views/messages/index.html.haml
> +      %ul.chat-main__header__current-group_list
<img width="1440" alt="キャプチャ" src="https://user-images.githubusercontent.com/49579149/56860763-169f4d00-69d5-11e9-959f-900ae12faee6.png">

2019-04-28 07:46 UTC, hiroki189 commented
<img width="1440" alt="キャプチャ" src="https://user-images.githubusercontent.com/49579149/56860773-29198680-69d5-11e9-90c0-f61e50e6abcf.png">

2019-04-28 07:46 UTC, hiroki189 commented
修正しました。

2019-04-28 08:02 UTC, yuki-uchida approved these changes
LGTMです

2019-04-28 08:21 UTC, merged