自動更新と修正
hiroki189/chat-space pull request #9
Opened 2019-06-02 08:27 UTC by hiroki189

2019-06-02 08:30 UTC, hiroki189 commented
#What
自動更新の実装

#Why
コードレビューをしてもらうため

2019-06-02 08:32 UTC, hiroki189 commented
動画キャプチャ
<img width="1440" alt="d10a76135553dc884d870778d2b2595d" src="https://user-images.githubusercontent.com/49579149/58758818-38539d00-855c-11e9-83e5-388e45c53ddd.png">

2019-06-02 08:36 UTC, hiroki189 commented
動画キャプチャ　文字だけ　画像だけ　文字と画像　
[f3c2620e107fd2af892e22a97e54a150.mp4.zip](https://github.com/hiroki189/chat-space/files/3244589/f3c2620e107fd2af892e22a97e54a150.mp4.zip)
[91278b821507b637499000f7a1a7eb9e.mp4.zip](https://github.com/hiroki189/chat-space/files/3244590/91278b821507b637499000f7a1a7eb9e.mp4.zip)
[6ca7f292151d87c2e9e2a3849b86b742.mp4.zip](https://github.com/hiroki189/chat-space/files/3244591/6ca7f292151d87c2e9e2a3849b86b742.mp4.zip)

2019-06-02 08:39 UTC, ghost requested changes

2019-06-02 08:39 UTC, hiroki5123 commented on app/views/messages/_message.html.haml
> +    %p.upper-message__data
ここdateじゃないんでしょうか・・・？

2019-06-02 08:39 UTC, hiroki5123 commented on app/views/api/messages/index.json.jbuilder
> +end
最後に空行入れましょう

2019-06-02 08:39 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +    respond_to do |format|
インデント一個奥です

2019-06-02 08:39 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    if(message.content && message.image){
ここ以下似ている部分が多いので、まとめられるところはまとめましょう

2019-06-03 06:52 UTC, hiroki189 commented on app/views/messages/_message.html.haml
> +    %p.upper-message__data
dateでしたので修正しました。

2019-06-03 06:53 UTC, hiroki189 commented on app/views/api/messages/index.json.jbuilder
> +end
空行入れました。

2019-06-03 06:53 UTC, hiroki189 commented on app/controllers/messages_controller.rb
> +    respond_to do |format|
修正しました。

2019-06-03 06:54 UTC, hiroki189 commented on app/assets/javascripts/message.js
> +    if(message.content && message.image){
まとめました。

2019-06-03 07:02 UTC, hiroki189 commented
送信の確認のために送った画像ファイルもpullリクエスに送ってしまいました。

2019-06-03 07:12 UTC, i-date reviewed
追加コメントいたしました。
また、プルリクページのFiles changedを見るとわかりやすいのですが、 public/uploads/以下の画像がpushされているので、gitignoreにpublic/uploads/以下がpushされないよう追記しましょう。

2019-06-03 07:12 UTC, i-date commented on app/assets/javascripts/message.js
> +  };
49-93行目ですが、重複箇所を省略するために変数と三項演算子を使用してみてはいかがでしょうか？
if文も必要なくなりますよ。
```
var 変数1 = 三項演算子でmessage.contentの真偽を判断して値を決定
var 変数2 = 三項演算子でmessage.imageの真偽を判断して値を決定
var html = 略
  変数1呼び出し
  変数2呼び出し
  略
```

2019-06-03 07:25 UTC, hiroki189 commented on app/assets/javascripts/message.js
> +  };
ご指摘ありがとうございます。修正しました。

2019-06-03 07:32 UTC, i-date approved these changes
拝見しましたが、特に問題ありません！LGTMとさせていただきます^^

ご参考までに。
レビューを依頼する際には、[WIP]は外してからレビューを依頼するといいでしょう^^
WIP = 作業中 なので、一通り作業が完了→WIP外す→レビュー依頼、という流れになります！

2019-06-03 07:37 UTC, hiroki189 commented
わざわざありがとうございます。
LGTMが出てから外すと勘違いしていました。

2019-06-03 07:38 UTC, merged